import { AreaId, FishSpecies, FishingRod, FishingBait, FishingRodId, FishingBaitId, FishRarity, Item } from '../types';

export const FISHING_RODS: Record<FishingRodId, FishingRod> = {
  rod_wooden: {
    id: 'rod_wooden',
    name: 'Wooden Rod',
    description: 'A simple carved willow rod. Reliable for basic river angling.',
    power: 1,
    rarityBonus: 1.0,
    barSizeMultiplier: 1.0,
    icon: '🎣',
    price: 50,
  },
  rod_iron: {
    id: 'rod_iron',
    name: 'Iron Rod',
    description: 'Forged by blacksmiths with flexible steel rings. Improved tension control.',
    power: 2,
    rarityBonus: 1.35,
    barSizeMultiplier: 1.15,
    icon: '🎣',
    price: 300,
  },
  rod_hunter: {
    id: 'rod_hunter',
    name: 'Hunter Rod',
    description: 'Reinforced with beast sinew. Grants great leverage against elusive lake predators.',
    power: 3,
    rarityBonus: 1.75,
    barSizeMultiplier: 1.3,
    icon: '🎣',
    price: 800,
  },
  rod_crystal: {
    id: 'rod_crystal',
    name: 'Crystal Rod',
    description: 'Infused with resonant mana crystals that hum and attract arcane fish.',
    power: 4,
    rarityBonus: 2.2,
    barSizeMultiplier: 1.45,
    icon: '🎣',
    price: 2000,
  },
  rod_celestial: {
    id: 'rod_celestial',
    name: 'Celestial Rod',
    description: 'A mythical rod forged with fallen star fragments. Attracts legendary sky leviathans.',
    power: 5,
    rarityBonus: 3.0,
    barSizeMultiplier: 1.6,
    icon: '✨',
    price: 5000,
  },
};

export const FISHING_BAITS: Record<FishingBaitId, FishingBait> = {
  bait_basic: {
    id: 'bait_basic',
    name: 'Basic Bait',
    description: 'Simple bread crumbs and dough balls. Attracts common fish quickly.',
    rarityBonus: 1.0,
    biteSpeedBonus: 1.0,
    icon: '🍞',
    price: 5,
  },
  bait_worm: {
    id: 'bait_worm',
    name: 'Earthworm Bait',
    description: 'Fresh squirming forest earthworms. Reliable bait for river and lake species.',
    rarityBonus: 1.2,
    biteSpeedBonus: 1.2,
    icon: '🪱',
    price: 15,
  },
  bait_insect: {
    id: 'bait_insect',
    name: 'Insect Bait',
    description: 'Glittering dragonfly and cricket blend. Attracts uncommon forest swimmers.',
    rarityBonus: 1.5,
    biteSpeedBonus: 1.4,
    icon: '🦗',
    price: 40,
  },
  bait_magic: {
    id: 'bait_magic',
    name: 'Magic Bait',
    description: 'Luminous paste glowing with aether energy. Substantially raises rare and epic fish rates.',
    rarityBonus: 2.2,
    biteSpeedBonus: 1.7,
    icon: '✨',
    price: 120,
  },
  bait_rare: {
    id: 'bait_rare',
    name: 'Celestial Amber Bait',
    description: 'Golden fossilized star sap. Highest chance to lure legendary apex swimmers.',
    rarityBonus: 3.5,
    biteSpeedBonus: 2.0,
    icon: '💎',
    price: 350,
  },
};

export const ALL_FISH: FishSpecies[] = [
  // 1. SKYFALL VILLAGE
  {
    id: 'fish_river_minnow',
    name: 'River Minnow',
    rarity: 'common',
    area: 'skyfall_village',
    areaName: 'Skyfall Village',
    icon: '🐟',
    value: 20,
    description: 'A nimble silver fish that thrives in clear shallow streams.',
    buffText: '+3% Movement Speed',
    sizeMin: 12,
    sizeMax: 22,
    weightMin: 0.2,
    weightMax: 0.6,
    buff: {
      id: 'buff_river_minnow',
      fishId: 'fish_river_minnow',
      name: 'Swift Current',
      rarity: 'common',
      icon: '💨',
      description: 'Increases player movement speed by 3%.',
      statBonus: { speedPct: 0.03 },
    },
  },
  {
    id: 'fish_golden_carp',
    name: 'Golden Carp',
    rarity: 'uncommon',
    area: 'skyfall_village',
    areaName: 'Skyfall Village',
    icon: '🐠',
    value: 65,
    description: 'A lustrous golden carp believed to bring good fortune to village anglers.',
    buffText: '+5% Max HP',
    sizeMin: 28,
    sizeMax: 48,
    weightMin: 1.2,
    weightMax: 3.4,
    buff: {
      id: 'buff_golden_carp',
      fishId: 'fish_golden_carp',
      name: 'Vitality Scale',
      rarity: 'uncommon',
      icon: '❤️',
      description: 'Increases maximum HP by 5%.',
      statBonus: { maxHpPct: 0.05 },
    },
  },
  {
    id: 'fish_village_sunfin',
    name: 'Sunken Sunfin',
    rarity: 'rare',
    area: 'skyfall_village',
    areaName: 'Skyfall Village',
    icon: '🐡',
    value: 180,
    description: 'A radiant orange fish that basks beneath the village waterwheel.',
    buffText: '+5% Attack Power',
    sizeMin: 35,
    sizeMax: 60,
    weightMin: 2.5,
    weightMax: 6.0,
    buff: {
      id: 'buff_village_sunfin',
      fishId: 'fish_village_sunfin',
      name: 'Solar Valor',
      rarity: 'rare',
      icon: '⚔️',
      description: 'Increases attack power by 5%.',
      statBonus: { attackPct: 0.05 },
    },
  },

  // 2. WHISPERING FOREST
  {
    id: 'fish_forest_trout',
    name: 'Forest Trout',
    rarity: 'common',
    area: 'whispering_forest',
    areaName: 'Whispering Forest',
    icon: '🐟',
    value: 30,
    description: 'Dappled green scales camouflage this agile fish among water lilies.',
    buffText: '+3% Movement Speed',
    sizeMin: 18,
    sizeMax: 32,
    weightMin: 0.4,
    weightMax: 1.2,
    buff: {
      id: 'buff_forest_trout',
      fishId: 'fish_forest_trout',
      name: 'Sylvan Step',
      rarity: 'common',
      icon: '🍃',
      description: 'Increases movement speed by 3%.',
      statBonus: { speedPct: 0.03 },
    },
  },
  {
    id: 'fish_leaf_fin',
    name: 'Emerald Leaf-Fin',
    rarity: 'uncommon',
    area: 'whispering_forest',
    areaName: 'Whispering Forest',
    icon: '🌿',
    value: 80,
    description: 'Fins that resemble tender oak leaves. Emits a gentle herbal scent.',
    buffText: '+5% Max HP',
    sizeMin: 24,
    sizeMax: 44,
    weightMin: 0.9,
    weightMax: 2.8,
    buff: {
      id: 'buff_leaf_fin',
      fishId: 'fish_leaf_fin',
      name: 'Grove Blessing',
      rarity: 'uncommon',
      icon: '💚',
      description: 'Increases maximum HP by 5%.',
      statBonus: { maxHpPct: 0.05 },
    },
  },
  {
    id: 'fish_fairy_tetra',
    name: 'Fairy Tetra',
    rarity: 'rare',
    area: 'whispering_forest',
    areaName: 'Whispering Forest',
    icon: '✨',
    value: 220,
    description: 'A luminescent fairy fish found near enchanted waterfall springs.',
    buffText: '+6% Skill Damage',
    sizeMin: 15,
    sizeMax: 28,
    weightMin: 0.3,
    weightMax: 0.9,
    buff: {
      id: 'buff_fairy_tetra',
      fishId: 'fish_fairy_tetra',
      name: 'Pixie Surge',
      rarity: 'rare',
      icon: '⚡',
      description: 'Increases skill & ultimate damage by 6%.',
      statBonus: { skillDamagePct: 0.06 },
    },
  },

  // 3. ANCIENT SANCTUM / RUINS
  {
    id: 'fish_stonefin',
    name: 'Stonefin Gudgeon',
    rarity: 'common',
    area: 'ancient_sanctum',
    areaName: 'Ancient Ruins',
    icon: '🐟',
    value: 45,
    description: 'Has hard slate-like scales that deflect underwater debris.',
    buffText: '+4% Defense',
    sizeMin: 20,
    sizeMax: 36,
    weightMin: 0.8,
    weightMax: 2.2,
    buff: {
      id: 'buff_stonefin',
      fishId: 'fish_stonefin',
      name: 'Granite Skin',
      rarity: 'common',
      icon: '🛡️',
      description: 'Increases defense by 4%.',
      statBonus: { defensePct: 0.04 },
    },
  },
  {
    id: 'fish_rune_koi',
    name: 'Runic Koi',
    rarity: 'rare',
    area: 'ancient_sanctum',
    areaName: 'Ancient Ruins',
    icon: '🔮',
    value: 260,
    description: 'Ancient glyphs are naturally inscribed across its shimmering scales.',
    buffText: '+6% Attack & +3% Crit',
    sizeMin: 32,
    sizeMax: 56,
    weightMin: 2.0,
    weightMax: 5.5,
    buff: {
      id: 'buff_rune_koi',
      fishId: 'fish_rune_koi',
      name: 'Rune Inscription',
      rarity: 'rare',
      icon: '✨',
      description: 'Increases attack power by 6% and critical strike chance by 3%.',
      statBonus: { attackPct: 0.06, critChanceBonus: 0.03 },
    },
  },
  {
    id: 'fish_ancient_colossus_fish',
    name: 'Sanctum Gilded Catfish',
    rarity: 'epic',
    area: 'ancient_sanctum',
    areaName: 'Ancient Ruins',
    icon: '🏆',
    value: 650,
    description: 'An ancient subterranean dweller that has guarded flooded sanctuary vaults for centuries.',
    buffText: '+8% Defense & +5% Crit',
    sizeMin: 70,
    sizeMax: 120,
    weightMin: 12.0,
    weightMax: 28.0,
    buff: {
      id: 'buff_ancient_catfish',
      fishId: 'fish_ancient_colossus_fish',
      name: 'Titan Bastion',
      rarity: 'epic',
      icon: '🛡️',
      description: 'Increases defense by 8% and critical chance by 5%.',
      statBonus: { defensePct: 0.08, critChanceBonus: 0.05 },
    },
  },

  // 4. FROZEN KINGDOM
  {
    id: 'fish_icefin',
    name: 'Glacial Icefin',
    rarity: 'uncommon',
    area: 'frozen_kingdom',
    areaName: 'Frozen Kingdom',
    icon: '❄️',
    value: 110,
    description: 'Its body remains near freezing temperature without freezing solid.',
    buffText: '+5% Max HP & Frost Ward',
    sizeMin: 25,
    sizeMax: 45,
    weightMin: 1.1,
    weightMax: 3.2,
    buff: {
      id: 'buff_icefin',
      fishId: 'fish_icefin',
      name: 'Glacial Chill',
      rarity: 'uncommon',
      icon: '❄️',
      description: 'Increases max HP by 5% and boosts defense.',
      statBonus: { maxHpPct: 0.05, defensePct: 0.03 },
    },
  },
  {
    id: 'fish_frost_carp',
    name: 'Frostbite Carp',
    rarity: 'rare',
    area: 'frozen_kingdom',
    areaName: 'Frozen Kingdom',
    icon: '🧊',
    value: 320,
    description: 'Found swimming under thick sheets of glacier ice in sub-zero caverns.',
    buffText: '+6% Attack & +5% Skill Dmg',
    sizeMin: 40,
    sizeMax: 70,
    weightMin: 3.5,
    weightMax: 9.0,
    buff: {
      id: 'buff_frost_carp',
      fishId: 'fish_frost_carp',
      name: 'Frost Edge',
      rarity: 'rare',
      icon: '⚔️',
      description: 'Increases attack power by 6% and skill damage by 5%.',
      statBonus: { attackPct: 0.06, skillDamagePct: 0.05 },
    },
  },
  {
    id: 'fish_aurora_leviathan',
    name: 'Aurora Borealis Trout',
    rarity: 'epic',
    area: 'frozen_kingdom',
    areaName: 'Frozen Kingdom',
    icon: '🌌',
    value: 850,
    description: 'Its translucent scales reflect the dancing emerald and violet aurora lights.',
    buffText: '+8% Defense & +6% Crit',
    sizeMin: 65,
    sizeMax: 110,
    weightMin: 8.0,
    weightMax: 20.0,
    buff: {
      id: 'buff_aurora_trout',
      fishId: 'fish_aurora_leviathan',
      name: 'Aurora Veil',
      rarity: 'epic',
      icon: '✨',
      description: 'Increases defense by 8% and critical chance by 6%.',
      statBonus: { defensePct: 0.08, critChanceBonus: 0.06 },
    },
  },

  // 5. VOLCANIC WASTELAND
  {
    id: 'fish_ember_minnow',
    name: 'Ember Minnow',
    rarity: 'uncommon',
    area: 'volcanic_wasteland',
    areaName: 'Volcanic Wasteland',
    icon: '🔥',
    value: 130,
    description: 'Swims in thermal sulfuric pools that would boil ordinary creatures.',
    buffText: '+5% Attack Power',
    sizeMin: 18,
    sizeMax: 34,
    weightMin: 0.6,
    weightMax: 1.8,
    buff: {
      id: 'buff_ember_minnow',
      fishId: 'fish_ember_minnow',
      name: 'Ignited Fury',
      rarity: 'uncommon',
      icon: '🔥',
      description: 'Increases attack power by 5%.',
      statBonus: { attackPct: 0.05 },
    },
  },
  {
    id: 'fish_magma_eel',
    name: 'Magma Eel',
    rarity: 'rare',
    area: 'volcanic_wasteland',
    areaName: 'Volcanic Wasteland',
    icon: '🌋',
    value: 380,
    description: 'Possesses obsidian plating that withstands pure liquid molten rock.',
    buffText: '+7% Attack & +5% Skill Dmg',
    sizeMin: 55,
    sizeMax: 95,
    weightMin: 4.0,
    weightMax: 12.0,
    buff: {
      id: 'buff_magma_eel',
      fishId: 'fish_magma_eel',
      name: 'Volcanic Wrath',
      rarity: 'rare',
      icon: '💥',
      description: 'Increases attack power by 7% and skill damage by 5%.',
      statBonus: { attackPct: 0.07, skillDamagePct: 0.05 },
    },
  },
  {
    id: 'fish_inferno_dragon_carp',
    name: 'Inferno Dragonfish',
    rarity: 'epic',
    area: 'volcanic_wasteland',
    areaName: 'Volcanic Wasteland',
    icon: '🐉',
    value: 950,
    description: 'Legend says this molten beast was born in the caldera of the deepest volcano.',
    buffText: '+9% Attack & +6% Crit',
    sizeMin: 80,
    sizeMax: 140,
    weightMin: 15.0,
    weightMax: 35.0,
    buff: {
      id: 'buff_inferno_dragonfish',
      fishId: 'fish_inferno_dragon_carp',
      name: 'Draconic Flame',
      rarity: 'epic',
      icon: '🔥',
      description: 'Increases attack power by 9% and critical strike chance by 6%.',
      statBonus: { attackPct: 0.09, critChanceBonus: 0.06 },
    },
  },

  // 6. SUNKEN CITY
  {
    id: 'fish_abyss_lantern',
    name: 'Abyssal Lanternfish',
    rarity: 'uncommon',
    area: 'sunken_city',
    areaName: 'Sunken City',
    icon: '🏮',
    value: 150,
    description: 'Guides its way through submerged marble ruins with a glowing bioluminescent bulb.',
    buffText: '+5% Max HP & +3% Speed',
    sizeMin: 22,
    sizeMax: 42,
    weightMin: 0.8,
    weightMax: 2.4,
    buff: {
      id: 'buff_abyss_lantern',
      fishId: 'fish_abyss_lantern',
      name: 'Abyssal Guidance',
      rarity: 'uncommon',
      icon: '💡',
      description: 'Increases max HP by 5% and movement speed by 3%.',
      statBonus: { maxHpPct: 0.05, speedPct: 0.03 },
    },
  },
  {
    id: 'fish_coral_swordtail',
    name: 'Coral Swordtail',
    rarity: 'rare',
    area: 'sunken_city',
    areaName: 'Sunken City',
    icon: '🪸',
    value: 420,
    description: 'Its razor sharp dorsal fin slices through sea kelp and sunken temple debris.',
    buffText: '+7% Attack & +4% Crit',
    sizeMin: 45,
    sizeMax: 80,
    weightMin: 3.0,
    weightMax: 7.5,
    buff: {
      id: 'buff_coral_swordtail',
      fishId: 'fish_coral_swordtail',
      name: 'Razor Coral',
      rarity: 'rare',
      icon: '⚔️',
      description: 'Increases attack by 7% and critical chance by 4%.',
      statBonus: { attackPct: 0.07, critChanceBonus: 0.04 },
    },
  },
  {
    id: 'fish_sunken_leviathan_juvenile',
    name: 'Tidecaller Leviathan',
    rarity: 'epic',
    area: 'sunken_city',
    areaName: 'Sunken City',
    icon: '🌊',
    value: 1100,
    description: 'Commands ocean currents that pulse within the sunken throne sanctum.',
    buffText: '+8% Defense & +8% Max HP',
    sizeMin: 90,
    sizeMax: 160,
    weightMin: 20.0,
    weightMax: 48.0,
    buff: {
      id: 'buff_tidecaller',
      fishId: 'fish_sunken_leviathan_juvenile',
      name: 'Oceanic Fortress',
      rarity: 'epic',
      icon: '🛡️',
      description: 'Increases defense by 8% and max HP by 8%.',
      statBonus: { defensePct: 0.08, maxHpPct: 0.08 },
    },
  },

  // 7. DARK SWAMP
  {
    id: 'fish_swamp_catfish',
    name: 'Murkwood Catfish',
    rarity: 'uncommon',
    area: 'dark_swamp',
    areaName: 'Dark Swamp',
    icon: '🐟',
    value: 160,
    description: 'Thrives in murky poisonous bogs where witch covens harvest rare spell components.',
    buffText: '+6% Defense',
    sizeMin: 30,
    sizeMax: 55,
    weightMin: 1.5,
    weightMax: 4.2,
    buff: {
      id: 'buff_swamp_catfish',
      fishId: 'fish_swamp_catfish',
      name: 'Bog Resilience',
      rarity: 'uncommon',
      icon: '🪵',
      description: 'Increases defense by 6%.',
      statBonus: { defensePct: 0.06 },
    },
  },
  {
    id: 'fish_shadow_koi',
    name: 'Shadowspore Koi',
    rarity: 'rare',
    area: 'dark_swamp',
    areaName: 'Dark Swamp',
    icon: '🍄',
    value: 460,
    description: 'Absorbs glowing swamp spore dust to manifest shadow illusions underwater.',
    buffText: '+7% Skill Dmg & +4% Crit',
    sizeMin: 38,
    sizeMax: 68,
    weightMin: 2.2,
    weightMax: 6.0,
    buff: {
      id: 'buff_shadow_koi',
      fishId: 'fish_shadow_koi',
      name: 'Spore Mirage',
      rarity: 'rare',
      icon: '✨',
      description: 'Increases skill damage by 7% and critical chance by 4%.',
      statBonus: { skillDamagePct: 0.07, critChanceBonus: 0.04 },
    },
  },
  {
    id: 'fish_witch_familiar_eel',
    name: 'Witchcraft Mystic Eel',
    rarity: 'epic',
    area: 'dark_swamp',
    areaName: 'Dark Swamp',
    icon: '🧪',
    value: 1200,
    description: 'An arcane serpentine creature imbued with dark alchemical sorcery.',
    buffText: '+9% Attack & +8% Skill Dmg',
    sizeMin: 85,
    sizeMax: 150,
    weightMin: 10.0,
    weightMax: 26.0,
    buff: {
      id: 'buff_witch_eel',
      fishId: 'fish_witch_familiar_eel',
      name: 'Coven Sorcery',
      rarity: 'epic',
      icon: '🔮',
      description: 'Increases attack power by 9% and skill damage by 8%.',
      statBonus: { attackPct: 0.09, skillDamagePct: 0.08 },
    },
  },

  // 8. SKY ISLANDS
  {
    id: 'fish_cloud_glider',
    name: 'Cloudfin Glider',
    rarity: 'rare',
    area: 'sky_islands',
    areaName: 'Sky Islands',
    icon: '☁️',
    value: 500,
    description: 'Uses broad winged pectoral fins to glide between floating islands.',
    buffText: '+5% Speed & +6% Attack',
    sizeMin: 35,
    sizeMax: 65,
    weightMin: 1.8,
    weightMax: 5.0,
    buff: {
      id: 'buff_cloud_glider',
      fishId: 'fish_cloud_glider',
      name: 'Aero Lift',
      rarity: 'rare',
      icon: '🪽',
      description: 'Increases movement speed by 5% and attack power by 6%.',
      statBonus: { speedPct: 0.05, attackPct: 0.06 },
    },
  },
  {
    id: 'fish_thunder_koi',
    name: 'Zephyr Thunder Koi',
    rarity: 'epic',
    area: 'sky_islands',
    areaName: 'Sky Islands',
    icon: '⚡',
    value: 1350,
    description: 'Stores electrostatic charges from storm clouds to unleash sonic surges.',
    buffText: '+9% Attack & +6% Crit',
    sizeMin: 60,
    sizeMax: 115,
    weightMin: 7.0,
    weightMax: 18.0,
    buff: {
      id: 'buff_thunder_koi',
      fishId: 'fish_thunder_koi',
      name: 'Storm Resonance',
      rarity: 'epic',
      icon: '⚡',
      description: 'Increases attack power by 9% and critical strike chance by 6%.',
      statBonus: { attackPct: 0.09, critChanceBonus: 0.06 },
    },
  },
  {
    id: 'fish_sky_dragon_fish',
    name: 'Sky Dragon Emperor',
    rarity: 'legendary',
    area: 'sky_islands',
    areaName: 'Sky Islands',
    icon: '🐉',
    value: 3000,
    description: 'A majestic creature venerated by the ancients as the sovereign of aerial realms.',
    buffText: '+10% Attack, +10% HP, +5% Crit',
    sizeMin: 120,
    sizeMax: 220,
    weightMin: 35.0,
    weightMax: 85.0,
    buff: {
      id: 'buff_sky_dragon',
      fishId: 'fish_sky_dragon_fish',
      name: 'Heavenly Sovereign',
      rarity: 'legendary',
      icon: '👑',
      description: 'Increases attack by 10%, max HP by 10%, and critical chance by 5%.',
      statBonus: { attackPct: 0.1, maxHpPct: 0.1, critChanceBonus: 0.05 },
    },
  },

  // 9. SHADOW CASTLE
  {
    id: 'fish_shadow_viper',
    name: 'Phantom Shadowfin',
    rarity: 'rare',
    area: 'shadow_castle',
    areaName: 'Shadow Castle',
    icon: '🌑',
    value: 580,
    description: 'Inhabits moat pools beneath the castle dungeon, shrouded in pure void mana.',
    buffText: '+7% Attack & +5% Skill Dmg',
    sizeMin: 40,
    sizeMax: 75,
    weightMin: 2.5,
    weightMax: 6.8,
    buff: {
      id: 'buff_shadow_viper',
      fishId: 'fish_shadow_viper',
      name: 'Void Surge',
      rarity: 'rare',
      icon: '🌑',
      description: 'Increases attack by 7% and skill damage by 5%.',
      statBonus: { attackPct: 0.07, skillDamagePct: 0.05 },
    },
  },
  {
    id: 'fish_void_eel',
    name: 'Abyssal Void Eel',
    rarity: 'epic',
    area: 'shadow_castle',
    areaName: 'Shadow Castle',
    icon: '🌌',
    value: 1500,
    description: 'Phases in and out of dimensional rifts to ambush unwary prey.',
    buffText: '+9% Defense & +7% Crit',
    sizeMin: 75,
    sizeMax: 135,
    weightMin: 12.0,
    weightMax: 30.0,
    buff: {
      id: 'buff_void_eel',
      fishId: 'fish_void_eel',
      name: 'Phantom Aegis',
      rarity: 'epic',
      icon: '🛡️',
      description: 'Increases defense by 9% and critical chance by 7%.',
      statBonus: { defensePct: 0.09, critChanceBonus: 0.07 },
    },
  },
  {
    id: 'fish_ancient_leviathan',
    name: 'Ancient Leviathan Behemoth',
    rarity: 'legendary',
    area: 'shadow_castle',
    areaName: 'Shadow Castle',
    icon: '👑',
    value: 3500,
    description: 'A colossal creature from before the Great Fracture, sleeping in the castle catacombs.',
    buffText: '+12% Attack, +10% HP, +6% Crit',
    sizeMin: 150,
    sizeMax: 260,
    weightMin: 50.0,
    weightMax: 120.0,
    buff: {
      id: 'buff_ancient_leviathan',
      fishId: 'fish_ancient_leviathan',
      name: 'Leviathan Domination',
      rarity: 'legendary',
      icon: '👑',
      description: 'Increases attack power by 12%, max HP by 10%, and critical chance by 6%.',
      statBonus: { attackPct: 0.12, maxHpPct: 0.1, critChanceBonus: 0.06 },
    },
  },

  // 10. CELESTIAL FORTRESS
  {
    id: 'fish_cosmic_ray',
    name: 'Starlight Cosmic Ray',
    rarity: 'rare',
    area: 'celestial_fortress',
    areaName: 'Celestial Fortress',
    icon: '✨',
    value: 700,
    description: 'Swims through suspended nebular energy pools inside the cosmic citadel.',
    buffText: '+8% Attack & +5% Speed',
    sizeMin: 50,
    sizeMax: 90,
    weightMin: 4.0,
    weightMax: 11.0,
    buff: {
      id: 'buff_cosmic_ray',
      fishId: 'fish_cosmic_ray',
      name: 'Astral Flow',
      rarity: 'rare',
      icon: '💫',
      description: 'Increases attack by 8% and movement speed by 5%.',
      statBonus: { attackPct: 0.08, speedPct: 0.05 },
    },
  },
  {
    id: 'fish_singularity_koi',
    name: 'Singularity Koi',
    rarity: 'epic',
    area: 'celestial_fortress',
    areaName: 'Celestial Fortress',
    icon: '🌀',
    value: 1800,
    description: 'Gravitational distortion surrounds this cosmic creature as it absorbs stardust.',
    buffText: '+10% Attack & +8% Skill Dmg',
    sizeMin: 80,
    sizeMax: 140,
    weightMin: 16.0,
    weightMax: 40.0,
    buff: {
      id: 'buff_singularity_koi',
      fishId: 'fish_singularity_koi',
      name: 'Cosmic Singularity',
      rarity: 'epic',
      icon: '🌀',
      description: 'Increases attack power by 10% and skill damage by 8%.',
      statBonus: { attackPct: 0.1, skillDamagePct: 0.08 },
    },
  },
  {
    id: 'fish_celestial_star_god',
    name: 'Celestial Dragon Resonator',
    rarity: 'legendary',
    area: 'celestial_fortress',
    areaName: 'Celestial Fortress',
    icon: '🌟',
    value: 5000,
    description: 'The supreme celestial fish carrying the pure harmonic pulse of the restored Sky Core.',
    buffText: '+15% Attack, +15% HP, +8% Crit',
    sizeMin: 180,
    sizeMax: 300,
    weightMin: 70.0,
    weightMax: 160.0,
    buff: {
      id: 'buff_celestial_star_god',
      fishId: 'fish_celestial_star_god',
      name: 'Celestial Supreme Harmony',
      rarity: 'legendary',
      icon: '🌟',
      description: 'Increases attack by 15%, max HP by 15%, and critical strike chance by 8%.',
      statBonus: { attackPct: 0.15, maxHpPct: 0.15, critChanceBonus: 0.08 },
    },
  },
];

export const FISH_BY_ID = ALL_FISH.reduce<Record<string, FishSpecies>>((acc, f) => {
  acc[f.id] = f;
  return acc;
}, {});

// Convert FishSpecies to regular game Item so it stores in Inventory smoothly
export function fishToInventoryItem(fish: FishSpecies): Item {
  return {
    id: fish.id,
    name: fish.name,
    description: `${fish.description} (${fish.buffText})`,
    category: 'fish',
    rarity: fish.rarity,
    icon: fish.icon,
    value: fish.value,
    stackable: true,
  };
}

// Convert Fishing Rod to Item
export function rodToInventoryItem(rod: FishingRod): Item {
  return {
    id: rod.id,
    name: rod.name,
    description: `${rod.description} (Fishing Power: ${rod.power})`,
    category: 'fishing_rod',
    rarity: rod.power >= 5 ? 'legendary' : rod.power >= 4 ? 'epic' : rod.power >= 3 ? 'rare' : 'common',
    icon: rod.icon,
    value: rod.price,
    stackable: false,
  };
}

// Convert Bait to Item
export function baitToInventoryItem(bait: FishingBait): Item {
  return {
    id: bait.id,
    name: bait.name,
    description: bait.description,
    category: 'bait',
    rarity: bait.rarityBonus >= 3 ? 'legendary' : bait.rarityBonus >= 2 ? 'rare' : 'common',
    icon: bait.icon,
    value: bait.price,
    stackable: true,
  };
}

// Weighted fish selection based on Area, Rod, and Bait
export function pickRandomFish(
  areaId: AreaId,
  rodId: FishingRodId,
  baitId: FishingBaitId | null
): FishSpecies {
  const available = ALL_FISH.filter((f) => f.area === areaId);
  const pool = available.length > 0 ? available : ALL_FISH.filter((f) => f.area === 'skyfall_village');

  const rod = FISHING_RODS[rodId] || FISHING_RODS.rod_wooden;
  const bait = baitId ? FISHING_BAITS[baitId] : null;

  const rarityMultiplier = rod.rarityBonus * (bait ? bait.rarityBonus : 1.0);

  // Calculate weights per rarity
  const rarityWeights: Record<FishRarity, number> = {
    common: 100,
    uncommon: 50 * rarityMultiplier,
    rare: 20 * rarityMultiplier,
    epic: 6 * rarityMultiplier,
    legendary: 1.2 * rarityMultiplier,
  };

  const weightedPool = pool.map((fish) => {
    return {
      fish,
      weight: rarityWeights[fish.rarity] || 10,
    };
  });

  const totalWeight = weightedPool.reduce((sum, item) => sum + item.weight, 0);
  let randomVal = Math.random() * totalWeight;

  for (const item of weightedPool) {
    if (randomVal <= item.weight) {
      return item.fish;
    }
    randomVal -= item.weight;
  }

  return pool[0];
}

// Generate realistic size and weight within species range
export function generateFishMeasurements(fish: FishSpecies): { size: number; weight: number } {
  const sizeVariance = Math.random();
  const size = Math.round((fish.sizeMin + (fish.sizeMax - fish.sizeMin) * sizeVariance) * 10) / 10;
  const weight = Math.round((fish.weightMin + (fish.weightMax - fish.weightMin) * (sizeVariance * 0.8 + Math.random() * 0.2)) * 100) / 100;
  return { size, weight };
}
