import { Item } from '../types';
import { ALL_FISH, FISHING_RODS, FISHING_BAITS, fishToInventoryItem, rodToInventoryItem, baitToInventoryItem } from './fishingData';

export const ITEMS: Record<string, Item> = {
  // --- WEAPONS ---
  iron_sword: {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'Aeron\'s trusted iron sword with a polished crossguard, carried when he plummeted from the sky.',
    category: 'weapon',
    rarity: 'common',
    icon: '⚔️',
    value: 25,
    stats: { attack: 10, critChance: 0.05 },
  },
  rusty_sword: {
    id: 'rusty_sword',
    name: 'Iron Sword',
    description: 'Aeron\'s trusted iron sword with a polished crossguard, carried when he plummeted from the sky.',
    category: 'weapon',
    rarity: 'common',
    icon: '⚔️',
    value: 25,
    stats: { attack: 10, critChance: 0.05 },
  },
  iron_broadsword: {
    id: 'iron_broadsword',
    name: 'Forged Iron Blade',
    description: 'Forged with precision by Blacksmith Brand using Skyfall iron ore.',
    category: 'weapon',
    rarity: 'rare',
    icon: '🗡️',
    value: 90,
    stats: { attack: 18, critChance: 0.10, skillDamage: 10 },
  },
  skyfall_blade: {
    id: 'skyfall_blade',
    name: 'Skyfall Tempest Blade',
    description: 'Imbued with a tiny flicker of celestial energy. Swings feel weightless.',
    category: 'weapon',
    rarity: 'epic',
    icon: '✨',
    value: 260,
    requiredBossId: 'mini_boss_treant',
    requiredBossName: 'Ancient Briar Treant',
    stats: { attack: 32, critChance: 0.15, skillDamage: 25 },
  },
  astral_saber: {
    id: 'astral_saber',
    name: 'Astral Core Saber',
    description: 'A legendary sword forged from pure resonant Sky Core fragments.',
    category: 'weapon',
    rarity: 'legendary',
    icon: '⚡',
    value: 650,
    requiredBossId: 'boss_talos',
    requiredBossName: 'Sky Guardian Talos',
    stats: { attack: 52, critChance: 0.25, skillDamage: 45 },
  },

  // --- ARMOR ---
  apprentice_tunic: {
    id: 'apprentice_tunic',
    name: 'Traveler Tunic',
    description: 'Standard woven wool tunic with light leather padding.',
    category: 'armor',
    rarity: 'common',
    icon: '🥋',
    value: 15,
    stats: { defense: 3, maxHp: 15 },
  },
  iron_mail: {
    id: 'iron_mail',
    name: 'Reinforced Iron Mail',
    description: 'Sturdy rings of interlocking iron. Protects against slashing claws.',
    category: 'armor',
    rarity: 'rare',
    icon: '🛡️',
    value: 75,
    stats: { defense: 9, maxHp: 40 },
  },
  skyfall_aegis_armor: {
    id: 'skyfall_aegis_armor',
    name: 'Skyfall Aegis Cuirass',
    description: 'Infused with defensive enchantments from the village elder.',
    category: 'armor',
    rarity: 'epic',
    icon: '🎽',
    value: 220,
    stats: { defense: 18, maxHp: 90 },
  },

  // --- ACCESSORIES ---
  copper_ring: {
    id: 'copper_ring',
    name: 'Carved Copper Ring',
    description: 'A simple token of courage. Enhances physical constitution.',
    category: 'accessory',
    rarity: 'common',
    icon: '💍',
    value: 25,
    stats: { maxHp: 20, attack: 2 },
  },
  windstep_boots: {
    id: 'windstep_boots',
    name: 'Windstep Talisman',
    description: 'Enables quick reflexes and faster skill replenishment.',
    category: 'accessory',
    rarity: 'rare',
    icon: '👢',
    value: 110,
    stats: { critChance: 0.08, skillDamage: 15, maxHp: 25 },
  },
  core_pendant: {
    id: 'core_pendant',
    name: 'Sky Core Pendant',
    description: 'Pulses with ethereal luminescence in rhythm with your heartbeat.',
    category: 'accessory',
    rarity: 'epic',
    icon: '🔮',
    value: 300,
    stats: { attack: 10, defense: 8, critChance: 0.12, maxHp: 60 },
  },

  // --- CONSUMABLES ---
  health_potion: {
    id: 'health_potion',
    name: 'Healing Potion',
    description: 'Brewed from wild forest herbs. Restores 60 Health Points instantly.',
    category: 'consumable',
    rarity: 'common',
    icon: '🧪',
    value: 15,
    effect: { healHp: 60 },
    stackable: true,
  },
  great_health_potion: {
    id: 'great_health_potion',
    name: 'Greater Vitality Brew',
    description: 'A potent concoction distilled from rare roots. Restores 140 Health Points.',
    category: 'consumable',
    rarity: 'rare',
    icon: '🍷',
    value: 45,
    effect: { healHp: 140 },
    stackable: true,
  },
  energy_elixir: {
    id: 'energy_elixir',
    name: 'Celestial Energy Elixir',
    description: 'Replenishes 60 Energy instantly, allowing rapid skill and ultimate execution.',
    category: 'consumable',
    rarity: 'common',
    icon: '💧',
    value: 20,
    effect: { restoreEnergy: 60 },
    stackable: true,
  },

  // --- MATERIALS ---
  iron_ore: {
    id: 'iron_ore',
    name: 'Skyfall Iron Ore',
    description: 'Raw high-grade ore needed by Blacksmith Brand to forge superior equipment.',
    category: 'material',
    rarity: 'common',
    icon: '🪨',
    value: 12,
    stackable: true,
  },
  forest_herb: {
    id: 'forest_herb',
    name: 'Luminescent Herb',
    description: 'Medicinal flora found in the Whispering Forest.',
    category: 'material',
    rarity: 'common',
    icon: '🌿',
    value: 8,
    stackable: true,
  },
  core_shard: {
    id: 'core_shard',
    name: 'Ancient Sky Core Shard',
    description: 'A crystallized fragment overflowing with primordial sky power.',
    category: 'material',
    rarity: 'epic',
    icon: '💎',
    value: 100,
    stackable: true,
  },

  // --- QUEST ITEMS ---
  elder_amulet: {
    id: 'elder_amulet',
    name: "Matthew's Lost Amulet",
    description: "An heirloom dropped by Elder Matthew near the entrance of Whispering Forest.",
    category: 'quest',
    rarity: 'rare',
    icon: '📿',
    value: 0,
    stackable: false,
  },
  sanctum_key: {
    id: 'sanctum_key',
    name: 'Golden Sanctum Key',
    description: 'A heavy brass key with celestial engraving. Unlocks the inner boss chamber door.',
    category: 'quest',
    rarity: 'epic',
    icon: '🔑',
    value: 0,
    stackable: false,
  },
  first_sky_core: {
    id: 'first_sky_core',
    name: 'Primary Sky Core Fragment',
    description: 'The ancient core artifact rescued from Sky Guardian Talos. Radiant light radiates outward.',
    category: 'quest',
    rarity: 'legendary',
    icon: '🌟',
    value: 0,
    stackable: false,
  },
  frostbite_blade: {
    id: 'frostbite_blade',
    name: 'Glacial Frostbite Blade',
    description: 'Forged from permafrost ice crystals in the Frozen Kingdom.',
    category: 'weapon',
    rarity: 'epic',
    icon: '❄️',
    value: 380,
    stats: { attack: 48, critChance: 0.16, skillDamage: 30 },
  },
  volcanic_flame_sword: {
    id: 'volcanic_flame_sword',
    name: 'Infernal Sunfang',
    description: 'Tempered in the molten magma veins of the Volcanic Wasteland.',
    category: 'weapon',
    rarity: 'epic',
    icon: '🔥',
    value: 520,
    stats: { attack: 68, critChance: 0.18, skillDamage: 45 },
  },
  tide_breaker_blade: {
    id: 'tide_breaker_blade',
    name: 'Abyssal Tidebreaker',
    description: 'Resonates with oceanic tides from the Sunken City ruins.',
    category: 'weapon',
    rarity: 'epic',
    icon: '🌊',
    value: 700,
    stats: { attack: 92, critChance: 0.22, skillDamage: 60 },
  },
  shadow_katana: {
    id: 'shadow_katana',
    name: 'Void Edge Katana',
    description: 'Forged from dark matter found inside the Shadow Castle.',
    category: 'weapon',
    rarity: 'legendary',
    icon: '🗡️',
    value: 950,
    stats: { attack: 125, critChance: 0.28, skillDamage: 80 },
  },
  skyfall_sovereign_sword: {
    id: 'skyfall_sovereign_sword',
    name: 'Skyfall Sovereign Blade',
    description: 'The ultimate celestial blade, containing the harmonic power of the restored Sky Core.',
    category: 'weapon',
    rarity: 'legendary',
    icon: '⚔️',
    value: 2000,
    stats: { attack: 180, critChance: 0.35, skillDamage: 120 },
  },
  glacial_frost_armor: {
    id: 'glacial_frost_armor',
    name: 'Glacial Frost Cuirass',
    description: 'Frozen plate armor that absorbs kinetic and thermal shocks.',
    category: 'armor',
    rarity: 'epic',
    icon: '🛡️',
    value: 360,
    stats: { defense: 28, maxHp: 160 },
  },
  inferno_plate: {
    id: 'inferno_plate',
    name: 'Obsidian Magma Carapace',
    description: 'Heavy obsidian plates cooled in holy waters.',
    category: 'armor',
    rarity: 'epic',
    icon: '🌋',
    value: 550,
    stats: { defense: 42, maxHp: 240 },
  },
  celestial_aegis: {
    id: 'celestial_aegis',
    name: 'Aegis of the Skyfall Knight',
    description: 'Aeron’s legendary armor restored to pristine celestial glory.',
    category: 'armor',
    rarity: 'legendary',
    icon: '👑',
    value: 1800,
    stats: { defense: 85, maxHp: 500 },
  },
  elixir_of_the_sky: {
    id: 'elixir_of_the_sky',
    name: 'Elixir of the Heavens',
    description: 'Divine ambrosia that fully restores 250 HP and 100 Energy.',
    category: 'consumable',
    rarity: 'legendary',
    icon: '🏺',
    value: 120,
    effect: { healHp: 250, restoreEnergy: 100 },
    stackable: true,
  },
};

// Automatically register all Fishing Rods into ITEMS
Object.values(FISHING_RODS).forEach((rod) => {
  ITEMS[rod.id] = rodToInventoryItem(rod);
});

// Automatically register all Fishing Baits into ITEMS
Object.values(FISHING_BAITS).forEach((bait) => {
  ITEMS[bait.id] = baitToInventoryItem(bait);
});

// Automatically register all Fish Species into ITEMS
ALL_FISH.forEach((fish) => {
  ITEMS[fish.id] = fishToInventoryItem(fish);
});

